name:                high-level-tensorflow
version:             0.1.0.0
github:              "schnecki/high-level-tensorflow"
license:             BSD3
author:              "Manuel Schneckenreither"
maintainer:          "manuel.schneckenreither@NOSPAM.uibk.ac.at"
copyright:           "2019 Manuel Schneckenreither"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            This is a high-level API to Tensorflow. It is used as a more convenient way to access the Tensorflow Haskell API (https://tensorflow.github.io/haskell/haddock/doc-index-All.html).
category:            Machine Learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/schnecki/high-level-tensorflow#readme>

dependencies:
- base >= 4.7 && < 5
- tensorflow >= 0.2.0.1
- tensorflow-core-ops
# - tensorflow-logging
# - tensorflow-mnist-input-data
- tensorflow-mnist
# - tensorflow-opgen
- tensorflow-ops
- tensorflow-proto
# - tensorflow-records-conduit
# - tensorflow-records


library:
  source-dirs: src

executables:
  high-level-tensorflow-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - high-level-tensorflow

tests:
  high-level-tensorflow-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - high-level-tensorflow
