resolver: lts-14.25
packages:
- .

extra-deps:
- git: https://github.com/tensorflow/haskell
  commit: 8cde4d6a277f188ca495d29096a62b36e8534a3f
  subdirs:
  - tensorflow
  - tensorflow-core-ops
  # - tensorflow-logging
  - tensorflow-mnist
  - tensorflow-mnist-input-data
  - tensorflow-opgen
  - tensorflow-ops
  - tensorflow-proto
  # - tensorflow-records
  # - tensorflow-records-conduit
  # - tensorflow-test

